/* JFSQLJJParser.java */
/* Generated By:JavaCC: Do not edit this line. JFSQLJJParser.java */
package fr.ogama.utils.parser;
import fr.ogama.utils.parser.model.*;
import java.util.Vector;
import fr.ogama.utils.parser.model.get.*;
import fr.ogama.utils.parser.model.get.expressions.logical.*;
import fr.ogama.utils.parser.model.get.expressions.comparator.*;
import java.io.DataInputStream;
import java.io.FileInputStream;
import fr.ogama.utils.parser.model.get.function.*;

public class JFSQLJJParser implements JFSQLJJParserConstants {
  public static void main(String args []) throws JFSQLParseException
  {
    try
    {
      JFSQLJJParser jfsqlParser = null;
      if (args.length == 1)
      {
        jfsqlParser = new JFSQLJJParser(new DataInputStream(new FileInputStream(args [0])));
        Vector v = jfsqlParser.JFSQLStatements();
        for (int i = 0; i < v.size(); i++)
        {
          Statement st = (Statement) v.elementAt(i);
          System.out.println(st.toString());
        }
      }
      else
      {
        throw new JFSQLParseException("No argument has been specified");
      }
    }
    catch (Exception e)
    {
      throw new JFSQLParseException(e.getMessage());
    }
  }

  final public Vector JFSQLStatements() throws ParseException {Vector v = new Vector();
  Statement s;
    label_1:
    while (true) {
      s = JFSQLStatement();
if (s == null) {if ("" != null) return v;}
      else v.addElement(s);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case K_GET:
      case K_AVG:
      case K_MIN:
      case K_MAX:
      case K_SUM:
      case K_COUNT:
      case K_ASDATESTRING:
      case K_ASDATE:
      case K_ASINTEGER:
      case K_ASLONG:
      case K_ASCONCAT:
      case K_ASEXTRACT:
      case K_ASSTRING:
      case S_NUMBER:
      case S_IDENTIFIER:
      case S_BIND:
      case S_CHAR_LITERAL:
      case S_QUOTED_IDENTIFIER:
      case 47:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
    }
{if ("" != null) return v;}
    throw new Error("Missing return statement in function");
  }

  final public Statement JFSQLStatement() throws ParseException {Statement s = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case K_GET:{
      s = getQuery();
      break;
      }
    case K_AVG:
    case K_MIN:
    case K_MAX:
    case K_SUM:
    case K_COUNT:
    case K_ASDATESTRING:
    case K_ASDATE:
    case K_ASINTEGER:
    case K_ASLONG:
    case K_ASCONCAT:
    case K_ASEXTRACT:
    case K_ASSTRING:
    case S_NUMBER:
    case S_IDENTIFIER:
    case S_BIND:
    case S_CHAR_LITERAL:
    case S_QUOTED_IDENTIFIER:
    case 47:{
      s = primaryExpression();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(46);
{if ("" != null) return s;}
    throw new Error("Missing return statement in function");
  }

  final public GetStatement getQuery() throws ParseException {GetStatement getStatement = new GetStatement();
  GetClause getClause = new GetClause();
  InClause inClause = new InClause();
  HavingClause havingClause = null;
  SortByClause sortByClause = null;
    getClause = getClause();
    inClause = inClause();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case K_HAVING:{
      havingClause = havingClause();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case K_SORT:{
      sortByClause = sortByClause();
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
getStatement.setGetClause(getClause);
    getStatement.setInClause(inClause);
    getStatement.setHavingClause(havingClause);
    getStatement.setSortByClause(sortByClause);
    {if ("" != null) return getStatement;}
    throw new Error("Missing return statement in function");
  }

  final public GetClause getClause() throws ParseException {GetClause getClause = new GetClause();
  Expression property = null;
  Token limit = null;
  boolean distinct = false;
    jj_consume_token(K_GET);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case S_NUMBER:{
      limit = jj_consume_token(S_NUMBER);
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case K_DISTINCT:{
      jj_consume_token(K_DISTINCT);
distinct = true;
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    property = primaryExpression();
getClause.setLimit(limit != null ? limit.toString() : null);
    getClause.setDistinct(distinct);
    getClause.setProperty(property);
    {if ("" != null) return getClause;}
    throw new Error("Missing return statement in function");
  }

  final public InClause inClause() throws ParseException {InClause inClause = new InClause();
  Vector pathItems = new Vector();
  PathItem pathItem;
    jj_consume_token(K_IN);
    jj_consume_token(47);
    pathItem = pathItem();
pathItems.addElement(pathItem);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 48:{
        ;
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        break label_2;
      }
      jj_consume_token(48);
      pathItem = pathItem();
pathItems.addElement(pathItem);
    }
    jj_consume_token(49);
inClause.setPathItems(pathItems);
    {if ("" != null) return inClause;}
    throw new Error("Missing return statement in function");
  }

  final public HavingClause havingClause() throws ParseException {HavingClause havingClause = null;
  Expression expression;
    jj_consume_token(K_HAVING);
    expression = expression();
if (expression != null)
    {
      havingClause = new HavingClause();
      havingClause.setExpression(expression);
    }
    {if ("" != null) return havingClause;}
    throw new Error("Missing return statement in function");
  }

  final public SortByClause sortByClause() throws ParseException {SortByClause sortByClause = new SortByClause();
  Token property;
  boolean isAscending = true; // default value

    jj_consume_token(K_SORT);
    jj_consume_token(K_BY);
    property = jj_consume_token(S_IDENTIFIER);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case K_ASCENDING:
    case K_DESCENDING:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case K_ASCENDING:{
        jj_consume_token(K_ASCENDING);
        break;
        }
      case K_DESCENDING:{
        jj_consume_token(K_DESCENDING);
isAscending = false;
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
sortByClause.setProperty(property != null ? property.toString() : null);
    sortByClause.setAscendingOrder(isAscending);
    {if ("" != null) return sortByClause;}
    throw new Error("Missing return statement in function");
  }

  final public PathItem pathItem() throws ParseException {PathItem pathItem = new PathItem();
  Token path = null;
  GetStatement subGetStatement = null;
  Token deep = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case S_CHAR_LITERAL:{
      path = jj_consume_token(S_CHAR_LITERAL);
      break;
      }
    case K_GET:{
      subGetStatement = subQuery();
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case K_DEEP:{
      jj_consume_token(K_DEEP);
      deep = jj_consume_token(S_NUMBER);
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      ;
    }
if (path != null)
    {
      pathItem.setPath(new Constant(path.toString().substring(1, path.toString().length() - 1), 3));
    }
    if (subGetStatement != null)
    {
      pathItem.setPath(subGetStatement);
    }
    pathItem.setDeep(deep != null ? deep.toString() : null);
    {if ("" != null) return pathItem;}
    throw new Error("Missing return statement in function");
  }

  final public Expression expression() throws ParseException {Expression e1, e2;
  ExpressionImpl e = null;
  boolean single = true;
    e1 = andExpression();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case K_OR:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_3;
      }
      jj_consume_token(K_OR);
      e2 = andExpression();
if (single)
      {
        e = new OrExpression("OR", e1);
      }
      single = false;
      e.addOperand(e2);
    }
{if ("" != null) return (single ? e1 : e);}
    throw new Error("Missing return statement in function");
  }

  final public Expression andExpression() throws ParseException {Expression e1, e2;
  ExpressionImpl e = null;
  boolean single = true;
    e1 = unaryLogicalExpression();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case K_AND:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_4;
      }
      jj_consume_token(K_AND);
      e2 = unaryLogicalExpression();
if (single)
      {
        e = new AndExpression("AND", e1);
      }
      single = false;
      e.addOperand(e2);
    }
{if ("" != null) return (single ? e1 : e);}
    throw new Error("Missing return statement in function");
  }

  final public Expression unaryLogicalExpression() throws ParseException {Expression e;
  ExpressionImpl not = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case K_NOT:{
      jj_consume_token(K_NOT);
not = new NotExpression("NOT");
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      ;
    }
    e = relationalExpression();
if (not != null)
    {
      not.addOperand(e);
    }
    {if ("" != null) return not == null ? e : not;}
    throw new Error("Missing return statement in function");
  }

  final public Expression relationalExpression() throws ParseException {Expression e1, eleft;
  ExpressionImpl eright = null;
  Vector v;
  boolean prior = false;
  boolean not = false;
    if (jj_2_1(2147483647)) {
      jj_consume_token(47);
      v = expressionList();
      jj_consume_token(49);
eleft = new ExpressionImpl(",");
      ((ExpressionImpl) eleft).setOperands(v);
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case K_AVG:
      case K_MIN:
      case K_MAX:
      case K_SUM:
      case K_COUNT:
      case K_ASDATESTRING:
      case K_ASDATE:
      case K_ASINTEGER:
      case K_ASLONG:
      case K_ASCONCAT:
      case K_ASEXTRACT:
      case K_ASSTRING:
      case S_NUMBER:
      case S_IDENTIFIER:
      case S_BIND:
      case S_CHAR_LITERAL:
      case S_QUOTED_IDENTIFIER:
      case 47:
      case 51:
      case 52:{
        e1 = simpleExpression();
if (prior) eleft = new ExpressionImpl("PRIOR", e1);
        else eleft = e1;
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case K_IN:
    case K_NOT:
    case K_LIKE:
    case K_BETWEEN:
    case K_MATCH:
    case 58:
    case 59:
    case 60:
    case 61:
    case 62:
    case 63:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 58:
      case 59:
      case 60:
      case 61:
      case 62:
      case 63:{
        eright = relationalOperatorExpression();
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        if (jj_2_2(2)) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case K_NOT:{
            jj_consume_token(K_NOT);
not = true;
            break;
            }
          default:
            jj_la1[15] = jj_gen;
            ;
          }
          eright = inClauseExpression();
        } else if (jj_2_3(2)) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case K_NOT:{
            jj_consume_token(K_NOT);
not = true;
            break;
            }
          default:
            jj_la1[16] = jj_gen;
            ;
          }
          eright = betweenClauseExpression();
        } else if (jj_2_4(2)) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case K_NOT:{
            jj_consume_token(K_NOT);
not = true;
            break;
            }
          default:
            jj_la1[17] = jj_gen;
            ;
          }
          eright = likeClauseExpression();
        } else if (jj_2_5(2)) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case K_NOT:{
            jj_consume_token(K_NOT);
not = true;
            break;
            }
          default:
            jj_la1[18] = jj_gen;
            ;
          }
          eright = matchClauseExpression();
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      ;
    }
if (eright == null) {if ("" != null) return eleft;}
    Vector v2 = eright.getOperands();
    if (v2 == null) v2 = new Vector(); //For IS NULL, which is unary!
    v2.insertElementAt(eleft, 0);
    eright.setOperands(v2);

    {if ("" != null) return not ? new NotExpression("NOT", eright) : eright;}
    throw new Error("Missing return statement in function");
  }

  final public Vector expressionList() throws ParseException {Vector v = new Vector(8);
  Expression e;
    e = simpleExpressionOrPreparedCol();
v.addElement(e);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 48:{
        ;
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        break label_5;
      }
      jj_consume_token(48);
      e = simpleExpressionOrPreparedCol();
v.addElement(e);
    }
{if ("" != null) return v;}
    throw new Error("Missing return statement in function");
  }

  final public ExpressionImpl relationalOperatorExpression() throws ParseException {ExpressionImpl e;
  Expression e1, eright;
  String op;
  String unaryOp = null;
    e = Relop();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 47:{
      jj_consume_token(47);
      e1 = subQuery();
      jj_consume_token(49);
if (unaryOp == null) eright = e1;
        else eright = new ExpressionImpl(unaryOp, e1);
      break;
      }
    case K_GET:
    case K_AVG:
    case K_MIN:
    case K_MAX:
    case K_SUM:
    case K_COUNT:
    case K_ASDATESTRING:
    case K_ASDATE:
    case K_ASINTEGER:
    case K_ASLONG:
    case K_ASCONCAT:
    case K_ASEXTRACT:
    case K_ASSTRING:
    case S_NUMBER:
    case S_IDENTIFIER:
    case S_BIND:
    case S_CHAR_LITERAL:
    case S_QUOTED_IDENTIFIER:
    case 50:
    case 51:
    case 52:{
      e1 = simpleExpressionOrPreparedCol();
if (unaryOp == null) eright = e1;
      else eright = new ExpressionImpl(unaryOp, e1);
      break;
      }
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
e.addOperand(eright);
    {if ("" != null) return e;}
    throw new Error("Missing return statement in function");
  }

  final public Expression simpleExpressionOrPreparedCol() throws ParseException {Expression e;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case K_AVG:
    case K_MIN:
    case K_MAX:
    case K_SUM:
    case K_COUNT:
    case K_ASDATESTRING:
    case K_ASDATE:
    case K_ASINTEGER:
    case K_ASLONG:
    case K_ASCONCAT:
    case K_ASEXTRACT:
    case K_ASSTRING:
    case S_NUMBER:
    case S_IDENTIFIER:
    case S_BIND:
    case S_CHAR_LITERAL:
    case S_QUOTED_IDENTIFIER:
    case 47:
    case 51:
    case 52:{
      e = simpleExpression();
{if ("" != null) return e;}
      break;
      }
    case 50:{
      e = preparedCol();
{if ("" != null) return e;}
      break;
      }
    case K_GET:{
      e = subQuery();
{if ("" != null) return e;}
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

// For prepared columns ("?")
  final public Expression preparedCol() throws ParseException {
    jj_consume_token(50);
{if ("" != null) return new ExpressionImpl("?");}
    throw new Error("Missing return statement in function");
  }

  final public ExpressionImpl inClauseExpression() throws ParseException {ExpressionImpl e;
  GetStatement q = null;
  Vector v = null;
    jj_consume_token(K_IN);
e = new In("IN");
    jj_consume_token(47);
    if (jj_2_6(2)) {
      v = expressionList();
e.setOperands(v);
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case K_GET:{
        q = subQuery();
e.addOperand(q);
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(49);
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
  }

  final public ExpressionImpl betweenClauseExpression() throws ParseException {ExpressionImpl e;
  Expression e1, e2;
    jj_consume_token(K_BETWEEN);
    e1 = simpleExpressionOrPreparedCol();
    jj_consume_token(K_AND);
    e2 = simpleExpressionOrPreparedCol();
e = new Between("BETWEEN", e1, e2);
    {if ("" != null) return e;}
    throw new Error("Missing return statement in function");
  }

  final public ExpressionImpl likeClauseExpression() throws ParseException {Expression eright;
  ExpressionImpl e;
    jj_consume_token(K_LIKE);
    eright = simpleExpressionOrPreparedCol();
e = new Like("LIKE", eright);
    {if ("" != null) return e;}
    throw new Error("Missing return statement in function");
  }

  final public ExpressionImpl matchClauseExpression() throws ParseException {Expression eright;
  ExpressionImpl e;
    jj_consume_token(K_MATCH);
    eright = simpleExpressionOrPreparedCol();
e = new Match("MATCH", eright);
    {if ("" != null) return e;}
    throw new Error("Missing return statement in function");
  }

  final public Expression simpleExpression() throws ParseException {Token op;
  Expression e1, e2;
  ExpressionImpl e = null;
    e1 = multiplicativeExpression();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 51:
      case 52:
      case 53:{
        ;
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 51:{
        op = jj_consume_token(51);
        break;
        }
      case 52:{
        op = jj_consume_token(52);
        break;
        }
      case 53:{
        op = jj_consume_token(53);
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      e2 = multiplicativeExpression();
e = new ExpressionImpl(op.toString(), e1);
      e.addOperand(e2);
      e1 = e;
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
  }

  final public Expression multiplicativeExpression() throws ParseException {Token op;
  Expression e1, e2;
  ExpressionImpl e = null;
    e1 = expotentExpression();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 54:
      case 55:{
        ;
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 54:{
        op = jj_consume_token(54);
        break;
        }
      case 55:{
        op = jj_consume_token(55);
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      e2 = expotentExpression();
e = new ExpressionImpl(op.toString(), e1);
      e.addOperand(e2);
      e1 = e;
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
  }

  final public Expression expotentExpression() throws ParseException {Token op;
  Expression e1, e2;
  ExpressionImpl e = null;
  boolean single = true;
    e1 = unaryExpression();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 56:{
        ;
        break;
        }
      default:
        jj_la1[29] = jj_gen;
        break label_8;
      }
      op = jj_consume_token(56);
      e2 = unaryExpression();
if (single) e = new ExpressionImpl(op.toString(), e1);
      single = false;
      e.addOperand(e2);
    }
{if ("" != null) return (single ? e1 : e);}
    throw new Error("Missing return statement in function");
  }

  final public Expression unaryExpression() throws ParseException {Token op = null;
  Expression e1, e;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 51:
    case 52:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 51:{
        op = jj_consume_token(51);
        break;
        }
      case 52:{
        op = jj_consume_token(52);
        break;
        }
      default:
        jj_la1[30] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[31] = jj_gen;
      ;
    }
    e1 = primaryExpression();
if (op == null) e = e1;
    else e = new ExpressionImpl(op.toString(), e1);
    {if ("" != null) return e;}
    throw new Error("Missing return statement in function");
  }

  final public Expression primaryExpression() throws ParseException {Token t;
  String s, s2, modifier = "";
  Expression e;
    if (jj_2_7(2147483647)) {
      s = outerJoinExpression();
{if ("" != null) return Constant.getProperty(s);}
    } else if (jj_2_8(2)) {
      e = functionCall();
{if ("" != null) return e;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case S_IDENTIFIER:
      case S_QUOTED_IDENTIFIER:{
        s = tableColumn();
{if ("" != null) return Constant.getProperty(s);}
        break;
        }
      case S_NUMBER:{
        t = jj_consume_token(S_NUMBER);
{if ("" != null) return new Constant(t.toString(), Constant.NUMBER);}
        break;
        }
      case S_CHAR_LITERAL:{
        t = jj_consume_token(S_CHAR_LITERAL);
s = t.toString();
    if (s.startsWith("\'")) s = s.substring(1);
    if (s.endsWith("\'")) s = s.substring(0, s.length() - 1);
    {if ("" != null) return new Constant(s, Constant.STRING);}
        break;
        }
      case S_BIND:{
        t = jj_consume_token(S_BIND);
{if ("" != null) return new Constant(t.toString(), Constant.STRING);}
        break;
        }
      case 47:{
        jj_consume_token(47);
        e = expression();
        jj_consume_token(49);
{if ("" != null) return e;}
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public AbstractFunction aggregateFunc() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case K_SUM:{
      t = jj_consume_token(K_SUM);
{if ("" != null) return new Sum(t.toString());}
      break;
      }
    case K_AVG:{
      t = jj_consume_token(K_AVG);
{if ("" != null) return new Avg(t.toString());}
      break;
      }
    case K_MAX:{
      t = jj_consume_token(K_MAX);
{if ("" != null) return new Max(t.toString());}
      break;
      }
    case K_MIN:{
      t = jj_consume_token(K_MIN);
{if ("" != null) return new Min(t.toString());}
      break;
      }
    case K_COUNT:{
      t = jj_consume_token(K_COUNT);
{if ("" != null) return new Count(t.toString());}
      break;
      }
    case K_ASDATESTRING:{
      t = jj_consume_token(K_ASDATESTRING);
{if ("" != null) return new AsDateString(t.toString());}
      break;
      }
    case K_ASDATE:{
      t = jj_consume_token(K_ASDATE);
{if ("" != null) return new AsDate(t.toString());}
      break;
      }
    case K_ASSTRING:{
      t = jj_consume_token(K_ASSTRING);
{if ("" != null) return new AsString(t.toString());}
      break;
      }
    case K_ASINTEGER:{
      t = jj_consume_token(K_ASINTEGER);
{if ("" != null) return new AsInteger(t.toString());}
      break;
      }
    case K_ASLONG:{
      t = jj_consume_token(K_ASLONG);
{if ("" != null) return new AsLong(t.toString());}
      break;
      }
    case K_ASCONCAT:{
      t = jj_consume_token(K_ASCONCAT);
{if ("" != null) return new Concat(t.toString());}
      break;
      }
    case K_ASEXTRACT:{
      t = jj_consume_token(K_ASEXTRACT);
{if ("" != null) return new Extract(t.toString());}
      break;
      }
    default:
      jj_la1[33] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ExpressionImpl functionCall() throws ParseException {Token t;
  String s = "";
  ExpressionImpl e = null;
  Vector parm = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case S_IDENTIFIER:{
      t = jj_consume_token(S_IDENTIFIER);
s = t.toString();
      break;
      }
    case K_AVG:
    case K_MIN:
    case K_MAX:
    case K_SUM:
    case K_COUNT:
    case K_ASDATESTRING:
    case K_ASDATE:
    case K_ASINTEGER:
    case K_ASLONG:
    case K_ASCONCAT:
    case K_ASEXTRACT:
    case K_ASSTRING:{
      e = aggregateFunc();
      break;
      }
    default:
      jj_la1[34] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(47);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case K_GET:
    case K_AVG:
    case K_MIN:
    case K_MAX:
    case K_SUM:
    case K_COUNT:
    case K_ASDATESTRING:
    case K_ASDATE:
    case K_ASINTEGER:
    case K_ASLONG:
    case K_ASCONCAT:
    case K_ASEXTRACT:
    case K_ASSTRING:
    case S_NUMBER:
    case S_IDENTIFIER:
    case S_BIND:
    case S_CHAR_LITERAL:
    case S_QUOTED_IDENTIFIER:
    case 47:
    case 50:
    case 51:
    case 52:{
      parm = expressionList();
      break;
      }
    default:
      jj_la1[35] = jj_gen;
      ;
    }
    jj_consume_token(49);
if (e == null)
    {
      {if (true) throw new JFSQLParseException("Undefined function " + s);}
    }
    int nparm = Utils.isCustomFunction(e != null ? e.getOperator() : "");
    if (nparm < 0) nparm = (Utils.isAggregate(e != null ? e.getOperator() : "") ? 1 : - 1);
    if (nparm < 0) {if (true) throw new JFSQLParseException("Undefined function : " + (e != null ? e.getOperator() : "null"));}
    if (nparm != Utils.VARIABLE_PLIST && nparm > 0)
    {
      if (parm == null || parm.size() != nparm) {if (true) throw new JFSQLParseException("Function " + e != null ? e.getOperator() : "null" + " should have " + nparm + " parameter(s)");}
    }
    e.setOperands(parm);
    {if ("" != null) return e;}
    throw new Error("Missing return statement in function");
  }

  final public String outerJoinExpression() throws ParseException {String s = null;
  String c = "";
    // user.table.col
      s = objectName();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 57:{
      jj_consume_token(57);
      c = objectName();
s += "." + c;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 57:{
        jj_consume_token(57);
        c = objectName();
s += "." + c;
        break;
        }
      default:
        jj_la1[36] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[37] = jj_gen;
      ;
    }
    jj_consume_token(47);
    jj_consume_token(51);
    jj_consume_token(49);
{if ("" != null) return s + "(+)";}
    throw new Error("Missing return statement in function");
  }

  final public GetStatement subQuery() throws ParseException {GetStatement q;
    q = getQuery();
{if ("" != null) return q;}
    throw new Error("Missing return statement in function");
  }

  final public ExpressionImpl Relop() throws ParseException {Token op;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 58:{
      op = jj_consume_token(58);
{if ("" != null) return new Equal(op.toString());}
      break;
      }
    case 59:{
      op = jj_consume_token(59);
{if ("" != null) return new UnEqual(op.toString());}
      break;
      }
    case 60:{
      op = jj_consume_token(60);
{if ("" != null) return new GreatherThan(op.toString());}
      break;
      }
    case 61:{
      op = jj_consume_token(61);
{if ("" != null) return new GreatherThanOrEqual(op.toString());}
      break;
      }
    case 62:{
      op = jj_consume_token(62);
{if ("" != null) return new LessThan(op.toString());}
      break;
      }
    case 63:{
      op = jj_consume_token(63);
{if ("" != null) return new LessThanOrEqual(op.toString());}
      break;
      }
    default:
      jj_la1[38] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public String tableColumn() throws ParseException {StringBuffer buf = new StringBuffer();
  String s;
    // user.table.column
      s = objectName();
buf.append(s);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 57:{
      jj_consume_token(57);
      s = objectName();
buf.append("." + s);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 57:{
        jj_consume_token(57);
        s = objectName();
buf.append("." + s);
        break;
        }
      default:
        jj_la1[39] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[40] = jj_gen;
      ;
    }
{if ("" != null) return buf.toString();}
    throw new Error("Missing return statement in function");
  }

  final public String objectName() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case S_IDENTIFIER:{
      t = jj_consume_token(S_IDENTIFIER);
{if ("" != null) return t.toString();}
      break;
      }
    case S_QUOTED_IDENTIFIER:{
      t = jj_consume_token(S_QUOTED_IDENTIFIER);
{if ("" != null) return t.toString();}
      break;
      }
    default:
      jj_la1[41] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_3R_44()
 {
    if (jj_scan_token(K_MAX)) return true;
    return false;
  }

  private boolean jj_3R_43()
 {
    if (jj_scan_token(K_AVG)) return true;
    return false;
  }

  private boolean jj_3R_87()
 {
    if (jj_3R_41()) return true;
    return false;
  }

  private boolean jj_3R_37()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) {
    jj_scanpos = xsp;
    if (jj_3R_45()) {
    jj_scanpos = xsp;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) {
    jj_scanpos = xsp;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_42()
 {
    if (jj_scan_token(K_SUM)) return true;
    return false;
  }

  private boolean jj_3R_74()
 {
    if (jj_scan_token(K_NOT)) return true;
    return false;
  }

  private boolean jj_3_6()
 {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_35()
 {
    if (jj_scan_token(S_QUOTED_IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_72()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_74()) jj_scanpos = xsp;
    if (jj_3R_75()) return true;
    return false;
  }

  private boolean jj_3R_34()
 {
    if (jj_scan_token(S_IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_25()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) return true;
    }
    return false;
  }

  private boolean jj_3R_11()
 {
    if (jj_scan_token(K_IN)) return true;
    if (jj_scan_token(47)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3R_87()) return true;
    }
    if (jj_scan_token(49)) return true;
    return false;
  }

  private boolean jj_3R_62()
 {
    if (jj_scan_token(47)) return true;
    if (jj_3R_65()) return true;
    if (jj_scan_token(49)) return true;
    return false;
  }

  private boolean jj_3R_61()
 {
    if (jj_scan_token(S_BIND)) return true;
    return false;
  }

  private boolean jj_3R_71()
 {
    if (jj_scan_token(57)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_60()
 {
    if (jj_scan_token(S_CHAR_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_73()
 {
    if (jj_scan_token(K_AND)) return true;
    if (jj_3R_72()) return true;
    return false;
  }

  private boolean jj_3R_40()
 {
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_59()
 {
    if (jj_scan_token(S_NUMBER)) return true;
    return false;
  }

  private boolean jj_3R_68()
 {
    if (jj_scan_token(57)) return true;
    if (jj_3R_25()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_71()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_69()
 {
    if (jj_3R_72()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_73()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_58()
 {
    if (jj_3R_64()) return true;
    return false;
  }

  private boolean jj_3_7()
 {
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_64()
 {
    if (jj_3R_25()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_68()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_33()
 {
    if (jj_3R_41()) return true;
    return false;
  }

  private boolean jj_3R_32()
 {
    if (jj_3R_40()) return true;
    return false;
  }

  private boolean jj_3_8()
 {
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_31()
 {
    if (jj_3R_9()) return true;
    return false;
  }

  private boolean jj_3R_23()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_31()) {
    jj_scanpos = xsp;
    if (jj_3R_32()) {
    jj_scanpos = xsp;
    if (jj_3R_33()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_55()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_57()) {
    jj_scanpos = xsp;
    if (jj_3_8()) {
    jj_scanpos = xsp;
    if (jj_3R_58()) {
    jj_scanpos = xsp;
    if (jj_3R_59()) {
    jj_scanpos = xsp;
    if (jj_3R_60()) {
    jj_scanpos = xsp;
    if (jj_3R_61()) {
    jj_scanpos = xsp;
    if (jj_3R_62()) return true;
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_57()
 {
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_97()
 {
    if (jj_scan_token(63)) return true;
    return false;
  }

  private boolean jj_3R_70()
 {
    if (jj_scan_token(K_OR)) return true;
    if (jj_3R_69()) return true;
    return false;
  }

  private boolean jj_3R_96()
 {
    if (jj_scan_token(62)) return true;
    return false;
  }

  private boolean jj_3R_65()
 {
    if (jj_3R_69()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_70()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_95()
 {
    if (jj_scan_token(61)) return true;
    return false;
  }

  private boolean jj_3R_86()
 {
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_94()
 {
    if (jj_scan_token(60)) return true;
    return false;
  }

  private boolean jj_3R_54()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(51)) {
    jj_scanpos = xsp;
    if (jj_scan_token(52)) return true;
    }
    return false;
  }

  private boolean jj_3R_93()
 {
    if (jj_scan_token(59)) return true;
    return false;
  }

  private boolean jj_3R_38()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_54()) jj_scanpos = xsp;
    if (jj_3R_55()) return true;
    return false;
  }

  private boolean jj_3R_85()
 {
    if (jj_scan_token(47)) return true;
    if (jj_3R_41()) return true;
    if (jj_scan_token(49)) return true;
    return false;
  }

  private boolean jj_3R_92()
 {
    if (jj_scan_token(58)) return true;
    return false;
  }

  private boolean jj_3R_84()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_92()) {
    jj_scanpos = xsp;
    if (jj_3R_93()) {
    jj_scanpos = xsp;
    if (jj_3R_94()) {
    jj_scanpos = xsp;
    if (jj_3R_95()) {
    jj_scanpos = xsp;
    if (jj_3R_96()) {
    jj_scanpos = xsp;
    if (jj_3R_97()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_80()
 {
    if (jj_3R_84()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_85()) {
    jj_scanpos = xsp;
    if (jj_3R_86()) return true;
    }
    return false;
  }

  private boolean jj_3R_99()
 {
    if (jj_scan_token(K_DEEP)) return true;
    if (jj_scan_token(S_NUMBER)) return true;
    return false;
  }

  private boolean jj_3R_98()
 {
    if (jj_3R_41()) return true;
    return false;
  }

  private boolean jj_3R_88()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(44)) {
    jj_scanpos = xsp;
    if (jj_3R_98()) return true;
    }
    xsp = jj_scanpos;
    if (jj_3R_99()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_41()
 {
    if (jj_3R_56()) return true;
    return false;
  }

  private boolean jj_3R_39()
 {
    if (jj_scan_token(56)) return true;
    if (jj_3R_38()) return true;
    return false;
  }

  private boolean jj_3R_29()
 {
    if (jj_3R_38()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_39()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_24()
 {
    if (jj_scan_token(48)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_36()
 {
    if (jj_scan_token(57)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_18()
 {
    if (jj_3R_23()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_24()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_101()
 {
    if (jj_scan_token(K_DESCENDING)) return true;
    return false;
  }

  private boolean jj_3R_100()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(25)) {
    jj_scanpos = xsp;
    if (jj_3R_101()) return true;
    }
    return false;
  }

  private boolean jj_3R_26()
 {
    if (jj_scan_token(57)) return true;
    if (jj_3R_25()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_36()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_91()
 {
    if (jj_scan_token(K_SORT)) return true;
    if (jj_scan_token(K_BY)) return true;
    if (jj_scan_token(S_IDENTIFIER)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_100()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_83()
 {
    if (jj_3R_91()) return true;
    return false;
  }

  private boolean jj_3R_19()
 {
    if (jj_3R_25()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_26()) jj_scanpos = xsp;
    if (jj_scan_token(47)) return true;
    if (jj_scan_token(51)) return true;
    if (jj_scan_token(49)) return true;
    return false;
  }

  private boolean jj_3R_30()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(54)) {
    jj_scanpos = xsp;
    if (jj_scan_token(55)) return true;
    }
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3R_16()
 {
    if (jj_scan_token(K_NOT)) return true;
    return false;
  }

  private boolean jj_3R_21()
 {
    if (jj_3R_29()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_30()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_14()
 {
    if (jj_scan_token(K_NOT)) return true;
    return false;
  }

  private boolean jj_3_5()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_16()) jj_scanpos = xsp;
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3R_90()
 {
    if (jj_scan_token(K_HAVING)) return true;
    if (jj_3R_65()) return true;
    return false;
  }

  private boolean jj_3R_67()
 {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_12()
 {
    if (jj_scan_token(K_NOT)) return true;
    return false;
  }

  private boolean jj_3R_28()
 {
    if (jj_3R_37()) return true;
    return false;
  }

  private boolean jj_3_4()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_14()) jj_scanpos = xsp;
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_22()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(51)) {
    jj_scanpos = xsp;
    if (jj_scan_token(52)) {
    jj_scanpos = xsp;
    if (jj_scan_token(53)) return true;
    }
    }
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_27()
 {
    if (jj_scan_token(S_IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_20()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_27()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) return true;
    }
    if (jj_scan_token(47)) return true;
    xsp = jj_scanpos;
    if (jj_3R_67()) jj_scanpos = xsp;
    if (jj_scan_token(49)) return true;
    return false;
  }

  private boolean jj_3R_89()
 {
    if (jj_scan_token(48)) return true;
    if (jj_3R_88()) return true;
    return false;
  }

  private boolean jj_3R_82()
 {
    if (jj_3R_90()) return true;
    return false;
  }

  private boolean jj_3R_9()
 {
    if (jj_3R_21()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_22()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_10()
 {
    if (jj_scan_token(K_NOT)) return true;
    return false;
  }

  private boolean jj_3_3()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_12()) jj_scanpos = xsp;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_81()
 {
    if (jj_scan_token(K_IN)) return true;
    if (jj_scan_token(47)) return true;
    if (jj_3R_88()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_89()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(49)) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_10()) jj_scanpos = xsp;
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3R_53()
 {
    if (jj_scan_token(K_ASEXTRACT)) return true;
    return false;
  }

  private boolean jj_3R_79()
 {
    if (jj_3R_80()) return true;
    return false;
  }

  private boolean jj_3R_78()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_79()) {
    jj_scanpos = xsp;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3_5()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_17()
 {
    if (jj_scan_token(K_MATCH)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_52()
 {
    if (jj_scan_token(K_ASCONCAT)) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_scan_token(47)) return true;
    if (jj_3R_9()) return true;
    if (jj_scan_token(48)) return true;
    return false;
  }

  private boolean jj_3R_51()
 {
    if (jj_scan_token(K_ASLONG)) return true;
    return false;
  }

  private boolean jj_3R_77()
 {
    if (jj_3R_9()) return true;
    return false;
  }

  private boolean jj_3R_50()
 {
    if (jj_scan_token(K_ASINTEGER)) return true;
    return false;
  }

  private boolean jj_3R_66()
 {
    if (jj_scan_token(K_DISTINCT)) return true;
    return false;
  }

  private boolean jj_3R_15()
 {
    if (jj_scan_token(K_LIKE)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_49()
 {
    if (jj_scan_token(K_ASSTRING)) return true;
    return false;
  }

  private boolean jj_3R_63()
 {
    if (jj_scan_token(K_GET)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(34)) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_66()) jj_scanpos = xsp;
    if (jj_3R_55()) return true;
    return false;
  }

  private boolean jj_3R_76()
 {
    if (jj_scan_token(47)) return true;
    if (jj_3R_18()) return true;
    if (jj_scan_token(49)) return true;
    return false;
  }

  private boolean jj_3R_48()
 {
    if (jj_scan_token(K_ASDATE)) return true;
    return false;
  }

  private boolean jj_3R_75()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_76()) {
    jj_scanpos = xsp;
    if (jj_3R_77()) return true;
    }
    xsp = jj_scanpos;
    if (jj_3R_78()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_47()
 {
    if (jj_scan_token(K_ASDATESTRING)) return true;
    return false;
  }

  private boolean jj_3R_13()
 {
    if (jj_scan_token(K_BETWEEN)) return true;
    if (jj_3R_23()) return true;
    if (jj_scan_token(K_AND)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_46()
 {
    if (jj_scan_token(K_COUNT)) return true;
    return false;
  }

  private boolean jj_3R_45()
 {
    if (jj_scan_token(K_MIN)) return true;
    return false;
  }

  private boolean jj_3R_56()
 {
    if (jj_3R_63()) return true;
    if (jj_3R_81()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_82()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_83()) jj_scanpos = xsp;
    return false;
  }

  /** Generated Token Manager. */
  public JFSQLJJParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[42];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xf8f80020,0xf8f80020,0x200,0x400,0x0,0x40,0x0,0x6000000,0x6000000,0x20,0x100,0x1000,0x2000,0x4000,0xf8f80000,0x4000,0x4000,0x4000,0x4000,0x0,0x3c080,0x0,0xf8f80020,0xf8f80020,0x20,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xf8f80000,0xf8f80000,0xf8f80020,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0xb907,0xb907,0x0,0x0,0x4,0x0,0x10000,0x0,0x0,0x1000,0x0,0x0,0x0,0x0,0x18b907,0x0,0x0,0x0,0x0,0xfc000000,0xfc000000,0x10000,0x1cb907,0x1cb907,0x0,0x380000,0x380000,0xc00000,0xc00000,0x1000000,0x180000,0x180000,0xb904,0x3,0x103,0x1cb907,0x2000000,0x2000000,0xfc000000,0x2000000,0x2000000,0x2100,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[8];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public JFSQLJJParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public JFSQLJJParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new JFSQLJJParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 42; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 42; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public JFSQLJJParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new JFSQLJJParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 42; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 42; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public JFSQLJJParser(JFSQLJJParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 42; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(JFSQLJJParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 42; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) {
       return;
    }

    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];

      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }

      for (int[] oldentry : jj_expentries) {
        if (oldentry.length == jj_expentry.length) {
          boolean isMatched = true;

          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              isMatched = false;
              break;
            }

          }
          if (isMatched) {
            jj_expentries.add(jj_expentry);
            break;
          }
        }
      }

      if (pos != 0) {
        jj_lasttokens[(jj_endpos = pos) - 1] = kind;
      }
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[64];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 42; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 64; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 8; i++) {
      try {
        JJCalls p = jj_2_rtns[i];

        do {
          if (p.gen > jj_gen) {
            jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
            switch (i) {
              case 0: jj_3_1(); break;
              case 1: jj_3_2(); break;
              case 2: jj_3_3(); break;
              case 3: jj_3_4(); break;
              case 4: jj_3_5(); break;
              case 5: jj_3_6(); break;
              case 6: jj_3_7(); break;
              case 7: jj_3_8(); break;
            }
          }
          p = p.next;
        } while (p != null);

        } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }

    p.gen = jj_gen + xla - jj_la; 
    p.first = token;
    p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
